// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9nuZ5sdnltoEoYOHW-scZk0msl2D9N-M',
    appId: '1:114336459925:web:553673824eaf3b7f967f9c',
    messagingSenderId: '114336459925',
    projectId: 'voicenote-6e2bc',
    authDomain: 'voicenote-6e2bc.firebaseapp.com',
    storageBucket: 'voicenote-6e2bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJsALfbU61wsCfex4qELkTlDma6uZ1Yk',
    appId: '1:114336459925:android:851000ad311358e3967f9c',
    messagingSenderId: '114336459925',
    projectId: 'voicenote-6e2bc',
    storageBucket: 'voicenote-6e2bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxYW-qXH4yJsR51uk01TTE_46xLe5nhAc',
    appId: '1:114336459925:ios:c8e528778beff811967f9c',
    messagingSenderId: '114336459925',
    projectId: 'voicenote-6e2bc',
    storageBucket: 'voicenote-6e2bc.firebasestorage.app',
    iosBundleId: 'com.example.voiceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxYW-qXH4yJsR51uk01TTE_46xLe5nhAc',
    appId: '1:114336459925:ios:c8e528778beff811967f9c',
    messagingSenderId: '114336459925',
    projectId: 'voicenote-6e2bc',
    storageBucket: 'voicenote-6e2bc.firebasestorage.app',
    iosBundleId: 'com.example.voiceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9nuZ5sdnltoEoYOHW-scZk0msl2D9N-M',
    appId: '1:114336459925:web:a11e9216853b031a967f9c',
    messagingSenderId: '114336459925',
    projectId: 'voicenote-6e2bc',
    authDomain: 'voicenote-6e2bc.firebaseapp.com',
    storageBucket: 'voicenote-6e2bc.firebasestorage.app',
  );
}
